name: Python Flask API Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Set up
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Dependency install
        run: |
          echo Installing requirements
          python -m pip install --upgrade pip
          pip install -r API/requirements.txt
      - name: Execute test 
        run: |
          echo Running tests
          python API/mainapp.py test
